FROM golang:alpine AS build

WORKDIR $GOPATH/src/app

ENV GO111MODULE=on
ENV GOPRIVATE=github.com/teyz
ENV GOOS=linux
ENV CGO_ENABLED=1

ARG GO_BUILDER_GITHUB_TOKEN=missing_token

COPY .. .

RUN apk update && apk upgrade && \
    apk add git musl-dev gcc ffmpeg && \
    mkdir /app && \
    go install github.com/cespare/reflex@latest && \
    go build -race -o /app/main cmd/main.go

EXPOSE 50051
